from enum import IntFlag, auto


class FatalError(IntFlag):
    FPWRL = auto()
    FTHERML = auto()
    FFREQL = auto()
    FVSFL = auto()
    CRL = auto()
    MRL = auto()
    CEL = auto()
    XEL = auto()
    FPWR = auto()
    FTHERM = auto()
    FFREQ = auto()
    FVSF = auto()
    DIS = auto()
    FATAL = auto()
    ALM = auto()
    SRQ = auto()


class WarningError(IntFlag):
    WPWRL = auto()
    WTHERML = auto()
    WFREQL = auto()
    WVSFL = auto()
    CRL = auto()
    MRL = auto()
    CEL = auto()
    XEL = auto()
    WPWR = auto()
    WTHERM = auto()
    WFREQ = auto()
    FVSF = auto()
    DIS = auto()
    FATAL = auto()
    ALM = auto()
    SRQ = auto()


class SQRTrigger(IntFlag):
    FPWRL = auto()
    FTHERML = auto()
    FFREQL = auto()
    FVSFL = auto()
    CRL = auto()
    MRL = auto()
    CEL = auto()
    XEL = auto()
    WPWRL = auto()
    WTHERML = auto()
    WFREQL = auto()
    WFVSFL = auto()
    DIS = auto()
    _13 = auto()
    _14 = auto()
    _15 = auto()


class FatalTrigger(IntFlag):
    FPWRL = auto()
    FTHERML = auto()
    FFREQL = auto()
    FVSFL = auto()
    _4 = auto()
    MRL = auto()
    _6 = auto()
    _7 = auto()
    WPWRL = auto()
    WTHERML = auto()
    WFREQL = auto()
    WFVSFL = auto()
    _12 = auto()
    _13 = auto()
    _14 = auto()
    _15 = auto()


class AlarmTrigger(IntFlag):
    FPWRL = auto()
    FTHERML = auto()
    FFREQL = auto()
    FVSFL = auto()
    _4 = auto()
    _5 = auto()
    _6 = auto()
    _7 = auto()
    WPWRL = auto()
    WTHERML = auto()
    WFREQL = auto()
    WFVSFL = auto()
    _12 = auto()
    _13 = auto()
    _14 = auto()
    _15 = auto()
